// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRedis creates a new instance of MockRedis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedis(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedis {
	mock := &MockRedis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedis is an autogenerated mock type for the Redis type
type MockRedis struct {
	mock.Mock
}

type MockRedis_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedis) EXPECT() *MockRedis_Expecter {
	return &MockRedis_Expecter{mock: &_m.Mock}
}

// CheckToRedis provides a mock function for the type MockRedis
func (_mock *MockRedis) CheckToRedis(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for CheckToRedis")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedis_CheckToRedis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckToRedis'
type MockRedis_CheckToRedis_Call struct {
	*mock.Call
}

// CheckToRedis is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedis_Expecter) CheckToRedis(ctx any, key any) *MockRedis_CheckToRedis_Call {
	return &MockRedis_CheckToRedis_Call{Call: _e.mock.On("CheckToRedis", ctx, key)}
}

func (_c *MockRedis_CheckToRedis_Call) Run(run func(ctx context.Context, key string)) *MockRedis_CheckToRedis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedis_CheckToRedis_Call) Return(b bool, err error) *MockRedis_CheckToRedis_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRedis_CheckToRedis_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockRedis_CheckToRedis_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFromRedis provides a mock function for the type MockRedis
func (_mock *MockRedis) DeleteFromRedis(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFromRedis")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedis_DeleteFromRedis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFromRedis'
type MockRedis_DeleteFromRedis_Call struct {
	*mock.Call
}

// DeleteFromRedis is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedis_Expecter) DeleteFromRedis(ctx any, key any) *MockRedis_DeleteFromRedis_Call {
	return &MockRedis_DeleteFromRedis_Call{Call: _e.mock.On("DeleteFromRedis", ctx, key)}
}

func (_c *MockRedis_DeleteFromRedis_Call) Run(run func(ctx context.Context, key string)) *MockRedis_DeleteFromRedis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedis_DeleteFromRedis_Call) Return(err error) *MockRedis_DeleteFromRedis_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedis_DeleteFromRedis_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockRedis_DeleteFromRedis_Call {
	_c.Call.Return(run)
	return _c
}

// SetToRedis provides a mock function for the type MockRedis
func (_mock *MockRedis) SetToRedis(ctx context.Context, key string, value any, exp time.Duration) error {
	ret := _mock.Called(ctx, key, value, exp)

	if len(ret) == 0 {
		panic("no return value specified for SetToRedis")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, exp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedis_SetToRedis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetToRedis'
type MockRedis_SetToRedis_Call struct {
	*mock.Call
}

// SetToRedis is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - exp time.Duration
func (_e *MockRedis_Expecter) SetToRedis(ctx any, key any, value any, exp any) *MockRedis_SetToRedis_Call {
	return &MockRedis_SetToRedis_Call{Call: _e.mock.On("SetToRedis", ctx, key, value, exp)}
}

func (_c *MockRedis_SetToRedis_Call) Run(run func(ctx context.Context, key string, value any, exp time.Duration)) *MockRedis_SetToRedis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRedis_SetToRedis_Call) Return(err error) *MockRedis_SetToRedis_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedis_SetToRedis_Call) RunAndReturn(run func(ctx context.Context, key string, value any, exp time.Duration) error) *MockRedis_SetToRedis_Call {
	_c.Call.Return(run)
	return _c
}
