// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mpayy/e-commerce/monolith/dependency"
	"github.com/Mpayy/e-commerce/monolith/internal/cart/delivery/http"
	repository2 "github.com/Mpayy/e-commerce/monolith/internal/cart/repository"
	"github.com/Mpayy/e-commerce/monolith/internal/cart/usecase"
	"github.com/Mpayy/e-commerce/monolith/internal/order/delivery/http"
	"github.com/Mpayy/e-commerce/monolith/internal/order/repository"
	usecase2 "github.com/Mpayy/e-commerce/monolith/internal/order/usecase"
	"github.com/Mpayy/e-commerce/monolith/internal/product/repository"
	usecase3 "github.com/Mpayy/e-commerce/monolith/internal/product/usecase"
	"github.com/Mpayy/e-commerce/monolith/internal/routes"
	"github.com/Mpayy/e-commerce/pkg/cache"
	"github.com/Mpayy/e-commerce/pkg/config"
	"github.com/Mpayy/e-commerce/pkg/engine"
	"github.com/Mpayy/e-commerce/pkg/jwt"
	"github.com/Mpayy/e-commerce/pkg/logger"
	"github.com/Mpayy/e-commerce/pkg/messaging"
	"github.com/Mpayy/e-commerce/pkg/middleware"
	"github.com/Mpayy/e-commerce/pkg/transaction"
	"github.com/Mpayy/e-commerce/pkg/validator"
	"github.com/Mpayy/e-commerce/proto/product/v1"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() (*dependency.App, func(), error) {
	configConfig := config.Load()
	loggerLogger := logger.NewLogger(configConfig)
	ginEngine := engine.NewGin(configConfig, loggerLogger)
	jwtToken := jwt.NewJwtToken(configConfig)
	client, cleanup := cache.NewRedisCli(configConfig, loggerLogger)
	redisSessionChecker := middleware.NewRedisSessionChecker(client)
	authMiddleware := middleware.NewAuthMiddleware(jwtToken, redisSessionChecker, loggerLogger)
	pool, cleanup2, err := dependency.NewPostgresPool(configConfig, loggerLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	db, err := dependency.NewGormDB(pool, configConfig, loggerLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	orderRepository := repository.NewOrderRepository(db)
	transactionTransaction := transaction.NewTransaction(db)
	cartRedisRepository := repository2.NewCartRedisRepository(client)
	clientConn, cleanup3, err := dependency.NewProductServiceConn(configConfig, loggerLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	productGRPCClient := productclient.NewProductGRPCClient(clientConn)
	cartUsecaseImpl := usecase.NewCartUsecase(cartRedisRepository, productGRPCClient, loggerLogger)
	channel, cleanup4, err := dependency.NewRabbitMQChannel(configConfig, loggerLogger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notificationEventPublisher := repository.NewNotificationEventPublisher(channel)
	orderUsecase := usecase2.NewOrderUsecase(orderRepository, transactionTransaction, loggerLogger, cartUsecaseImpl, productGRPCClient, notificationEventPublisher)
	orderHandler := orderhttp.NewOrderHandler(orderUsecase, loggerLogger)
	validate := validator.NewValidator()
	cartHandler := carthttp.NewCartHandler(cartUsecaseImpl, cartUsecaseImpl, validate)
	router := routes.NewRouter(ginEngine, authMiddleware, orderHandler, cartHandler, loggerLogger)
	app := dependency.NewApp(router, db, configConfig, loggerLogger, channel)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var productSet = wire.NewSet(productclient.NewProductGRPCClient, wire.Bind(new(usecase3.ProductService), new(*productclient.ProductGRPCClient)))

var cartSet = wire.NewSet(repository2.NewCartRedisRepository, usecase.NewCartUsecase, wire.Bind(new(usecase.CartService), new(*usecase.CartUsecaseImpl)), wire.Bind(new(usecase.CartUsecase), new(*usecase.CartUsecaseImpl)), carthttp.NewCartHandler)

var orderSet = wire.NewSet(repository.NewOrderRepository, repository.NewNotificationEventPublisher, wire.Bind(new(usecase2.EventPublisher), new(*repository.NotificationEventPublisher)), usecase2.NewOrderUsecase, orderhttp.NewOrderHandler)

var middlewareSet = wire.NewSet(middleware.NewRedisSessionChecker, wire.Bind(new(middleware.SessionChecker), new(*middleware.RedisSessionChecker)), middleware.NewAuthMiddleware)

var InfrastructureSet = wire.NewSet(config.Load, logger.NewLogger, validator.NewValidator, cache.NewRedisCli, engine.NewGin, messaging.NewRabbitMQConn, dependency.NewGormDB, dependency.NewRabbitMQChannel, dependency.NewPostgresPool, dependency.NewProductServiceConn, productv1.NewProductServiceClient)
