// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mpayy/e-commerce/monolith/dependency"
	"github.com/Mpayy/e-commerce/monolith/internal/cart/delivery/http"
	repository3 "github.com/Mpayy/e-commerce/monolith/internal/cart/repository"
	usecase2 "github.com/Mpayy/e-commerce/monolith/internal/cart/usecase"
	"github.com/Mpayy/e-commerce/monolith/internal/order/delivery/http"
	repository2 "github.com/Mpayy/e-commerce/monolith/internal/order/repository"
	usecase3 "github.com/Mpayy/e-commerce/monolith/internal/order/usecase"
	"github.com/Mpayy/e-commerce/monolith/internal/product/repository"
	"github.com/Mpayy/e-commerce/monolith/internal/routes"
	"github.com/Mpayy/e-commerce/monolith/internal/user/delivery/http"
	"github.com/Mpayy/e-commerce/monolith/internal/user/repository"
	"github.com/Mpayy/e-commerce/monolith/internal/user/usecase"
	"github.com/Mpayy/e-commerce/pkg/cache"
	"github.com/Mpayy/e-commerce/pkg/config"
	"github.com/Mpayy/e-commerce/pkg/database"
	"github.com/Mpayy/e-commerce/pkg/engine"
	"github.com/Mpayy/e-commerce/pkg/jwt"
	"github.com/Mpayy/e-commerce/pkg/logger"
	"github.com/Mpayy/e-commerce/pkg/middleware"
	"github.com/Mpayy/e-commerce/pkg/transaction"
	"github.com/Mpayy/e-commerce/pkg/validator"
	"github.com/Mpayy/e-commerce/proto/product/v1"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() (*dependency.App, func(), error) {
	configConfig := config.Load()
	loggerLogger := logger.NewLogger(configConfig)
	ginEngine := engine.NewGin(configConfig, loggerLogger)
	jwtToken := jwt.NewJwtToken(configConfig)
	client, cleanup := cache.NewRedisCli(configConfig, loggerLogger)
	userRedisRepository := repository.NewUserRedisRepository(client)
	authMiddleware := middleware.NewAuthMiddleware(jwtToken, userRedisRepository, loggerLogger)
	db, cleanup2, err := database.NewPostgresDB(configConfig, loggerLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	gormDB, err := dependency.NewGormDB(db, configConfig, loggerLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	transactionTransaction := transaction.NewTransaction(gormDB)
	userUsecase := usecase.NewUserUsecase(userRepository, userRedisRepository, transactionTransaction, loggerLogger, jwtToken)
	validate := validator.NewValidator()
	userHandler := http.NewUserHandler(userUsecase, validate)
	orderRepository := repository2.NewOrderRepository(gormDB)
	cartRedisRepository := repository3.NewCartRedisRepository(client)
	clientConn, cleanup3, err := dependency.NewProductServiceConn(configConfig, loggerLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	productService := productclient.NewProductGRPCClient(clientConn)
	cartUsecaseImpl := usecase2.NewCartUsecase(cartRedisRepository, productService, loggerLogger)
	orderUsecase := usecase3.NewOrderUsecase(orderRepository, transactionTransaction, loggerLogger, cartUsecaseImpl, productService)
	orderHandler := orderhttp.NewOrderHandler(orderUsecase, loggerLogger)
	cartHandler := carthttp.NewCartHandler(cartUsecaseImpl, cartUsecaseImpl, validate)
	router := routes.NewRouter(ginEngine, authMiddleware, userHandler, orderHandler, cartHandler, loggerLogger)
	app := dependency.NewApp(router, gormDB, configConfig, loggerLogger)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var userSet = wire.NewSet(repository.NewUserRedisRepository, wire.Bind(new(middleware.SessionChecker), new(repository.UserRedisRepository)), repository.NewUserRepository, usecase.NewUserUsecase, http.NewUserHandler)

var productSet = wire.NewSet(dependency.NewProductServiceConn, productv1.NewProductServiceClient, productclient.NewProductGRPCClient)

var cartSet = wire.NewSet(repository3.NewCartRedisRepository, usecase2.NewCartUsecase, wire.Bind(new(usecase2.CartService), new(*usecase2.CartUsecaseImpl)), wire.Bind(new(usecase2.CartUsecase), new(*usecase2.CartUsecaseImpl)), carthttp.NewCartHandler)

var orderSet = wire.NewSet(repository2.NewOrderRepository, usecase3.NewOrderUsecase, orderhttp.NewOrderHandler)

var InfrastructureSet = wire.NewSet(config.Load, logger.NewLogger, validator.NewValidator, cache.NewRedisCli, engine.NewGin, database.NewPostgresDB, dependency.NewGormDB)
