all: false
pkgname: "mocks"

packages:
  github.com/Mpayy/e-commerce/services/user-service/internal/user/repository:
  github.com/Mpayy/e-commerce/services/product-service/internal/product/repository:
  github.com/Mpayy/e-commerce/services/product-service/internal/product/usecase:
  github.com/Mpayy/e-commerce/services/order-service/internal/cart/usecase:
  github.com/Mpayy/e-commerce/services/order-service/internal/cart/repository:
  github.com/Mpayy/e-commerce/services/order-service/internal/order/repository:
  github.com/Mpayy/e-commerce/services/order-service/internal/order/usecase:
  github.com/Mpayy/e-commerce/services/order-service/internal/product/usecase:
  github.com/Mpayy/e-commerce/pkg/jwt:
  github.com/Mpayy/e-commerce/proto/product/v1: