services:
  api-gateway:
    image: ghcr.io/mpayy/e-commerce-api-gateway:latest
    restart: unless-stopped
    ports:
    - "8080:8080"
    env_file: [.env]
    environment:
      USER_SERVICE_ADDR: http://user-service:8082
      PRODUCT_SERVICE_HTTP_ADDR: http://product-service:8081
      ORDER_SERVICE_ADDR: http://order-service:8083
    depends_on:
      user-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - ecommerce-network

  product-service:
    image: ghcr.io/mpayy/e-commerce-product-service:latest
    restart: unless-stopped
    volumes:
      - product_images:/app/uploads/products
    env_file: [.env]
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8081/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 15s
    networks:
      - ecommerce-network

  user-service:
    image: ghcr.io/mpayy/e-commerce-user-service:latest
    restart: unless-stopped
    env_file: [.env]
    environment:
      DATABASE_NAME: user_db
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8082/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 15s
    networks:
      - ecommerce-network

  notification-consumer:
    image: ghcr.io/mpayy/e-commerce-notification-consumer:latest
    restart: unless-stopped
    env_file: [.env]
    environment:
      DATABASE_NAME: notification_db
    networks:
      - ecommerce-network

  order-service:
    image: ghcr.io/mpayy/e-commerce-order-service:latest
    restart: unless-stopped
    env_file: [.env]
    environment:
      DATABASE_NAME: order_db
      PRODUCT_SERVICE_ADDR: product-service:50051
    depends_on:
      product-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8083/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 15s
    networks:
      - ecommerce-network
    
volumes:
  product_images:
    driver: local

networks:
  ecommerce-network:
    driver: bridge