// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/e-commerce/monolith/internal/product/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProductService creates a new instance of MockProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductService {
	mock := &MockProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductService is an autogenerated mock type for the ProductService type
type MockProductService struct {
	mock.Mock
}

type MockProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductService) EXPECT() *MockProductService_Expecter {
	return &MockProductService_Expecter{mock: &_m.Mock}
}

// BulkDecreaseStock provides a mock function for the type MockProductService
func (_mock *MockProductService) BulkDecreaseStock(ctx context.Context, checkoutID string, items []entity.BulkDecreaseStock) error {
	ret := _mock.Called(ctx, checkoutID, items)

	if len(ret) == 0 {
		panic("no return value specified for BulkDecreaseStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []entity.BulkDecreaseStock) error); ok {
		r0 = returnFunc(ctx, checkoutID, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductService_BulkDecreaseStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDecreaseStock'
type MockProductService_BulkDecreaseStock_Call struct {
	*mock.Call
}

// BulkDecreaseStock is a helper method to define mock.On call
//   - ctx context.Context
//   - checkoutID string
//   - items []entity.BulkDecreaseStock
func (_e *MockProductService_Expecter) BulkDecreaseStock(ctx any, checkoutID any, items any) *MockProductService_BulkDecreaseStock_Call {
	return &MockProductService_BulkDecreaseStock_Call{Call: _e.mock.On("BulkDecreaseStock", ctx, checkoutID, items)}
}

func (_c *MockProductService_BulkDecreaseStock_Call) Run(run func(ctx context.Context, checkoutID string, items []entity.BulkDecreaseStock)) *MockProductService_BulkDecreaseStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []entity.BulkDecreaseStock
		if args[2] != nil {
			arg2 = args[2].([]entity.BulkDecreaseStock)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProductService_BulkDecreaseStock_Call) Return(err error) *MockProductService_BulkDecreaseStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductService_BulkDecreaseStock_Call) RunAndReturn(run func(ctx context.Context, checkoutID string, items []entity.BulkDecreaseStock) error) *MockProductService_BulkDecreaseStock_Call {
	_c.Call.Return(run)
	return _c
}

// BulkRestoreStock provides a mock function for the type MockProductService
func (_mock *MockProductService) BulkRestoreStock(ctx context.Context, checkoutID string) error {
	ret := _mock.Called(ctx, checkoutID)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestoreStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, checkoutID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductService_BulkRestoreStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkRestoreStock'
type MockProductService_BulkRestoreStock_Call struct {
	*mock.Call
}

// BulkRestoreStock is a helper method to define mock.On call
//   - ctx context.Context
//   - checkoutID string
func (_e *MockProductService_Expecter) BulkRestoreStock(ctx any, checkoutID any) *MockProductService_BulkRestoreStock_Call {
	return &MockProductService_BulkRestoreStock_Call{Call: _e.mock.On("BulkRestoreStock", ctx, checkoutID)}
}

func (_c *MockProductService_BulkRestoreStock_Call) Run(run func(ctx context.Context, checkoutID string)) *MockProductService_BulkRestoreStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductService_BulkRestoreStock_Call) Return(err error) *MockProductService_BulkRestoreStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductService_BulkRestoreStock_Call) RunAndReturn(run func(ctx context.Context, checkoutID string) error) *MockProductService_BulkRestoreStock_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProductID provides a mock function for the type MockProductService
func (_mock *MockProductService) GetByProductID(ctx context.Context, id uint) (*entity.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByProductID")
	}

	var r0 *entity.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*entity.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *entity.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductService_GetByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProductID'
type MockProductService_GetByProductID_Call struct {
	*mock.Call
}

// GetByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockProductService_Expecter) GetByProductID(ctx any, id any) *MockProductService_GetByProductID_Call {
	return &MockProductService_GetByProductID_Call{Call: _e.mock.On("GetByProductID", ctx, id)}
}

func (_c *MockProductService_GetByProductID_Call) Run(run func(ctx context.Context, id uint)) *MockProductService_GetByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductService_GetByProductID_Call) Return(product *entity.Product, err error) *MockProductService_GetByProductID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductService_GetByProductID_Call) RunAndReturn(run func(ctx context.Context, id uint) (*entity.Product, error)) *MockProductService_GetByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductsByIDs provides a mock function for the type MockProductService
func (_mock *MockProductService) GetProductsByIDs(ctx context.Context, ids []uint) ([]entity.Product, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsByIDs")
	}

	var r0 []entity.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint) ([]entity.Product, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint) []entity.Product); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductService_GetProductsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductsByIDs'
type MockProductService_GetProductsByIDs_Call struct {
	*mock.Call
}

// GetProductsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockProductService_Expecter) GetProductsByIDs(ctx any, ids any) *MockProductService_GetProductsByIDs_Call {
	return &MockProductService_GetProductsByIDs_Call{Call: _e.mock.On("GetProductsByIDs", ctx, ids)}
}

func (_c *MockProductService_GetProductsByIDs_Call) Run(run func(ctx context.Context, ids []uint)) *MockProductService_GetProductsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint
		if args[1] != nil {
			arg1 = args[1].([]uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductService_GetProductsByIDs_Call) Return(products []entity.Product, err error) *MockProductService_GetProductsByIDs_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockProductService_GetProductsByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []uint) ([]entity.Product, error)) *MockProductService_GetProductsByIDs_Call {
	_c.Call.Return(run)
	return _c
}
