// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Mpayy/e-commerce/pkg/jwt"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJwtToken creates a new instance of MockJwtToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwtToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwtToken {
	mock := &MockJwtToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwtToken is an autogenerated mock type for the JwtToken type
type MockJwtToken struct {
	mock.Mock
}

type MockJwtToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwtToken) EXPECT() *MockJwtToken_Expecter {
	return &MockJwtToken_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockJwtToken
func (_mock *MockJwtToken) Create(auth *jwt.Auth) (string, error) {
	ret := _mock.Called(auth)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*jwt.Auth) (string, error)); ok {
		return returnFunc(auth)
	}
	if returnFunc, ok := ret.Get(0).(func(*jwt.Auth) string); ok {
		r0 = returnFunc(auth)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*jwt.Auth) error); ok {
		r1 = returnFunc(auth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwtToken_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockJwtToken_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - auth *jwt.Auth
func (_e *MockJwtToken_Expecter) Create(auth any) *MockJwtToken_Create_Call {
	return &MockJwtToken_Create_Call{Call: _e.mock.On("Create", auth)}
}

func (_c *MockJwtToken_Create_Call) Run(run func(auth *jwt.Auth)) *MockJwtToken_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *jwt.Auth
		if args[0] != nil {
			arg0 = args[0].(*jwt.Auth)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJwtToken_Create_Call) Return(s string, err error) *MockJwtToken_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJwtToken_Create_Call) RunAndReturn(run func(auth *jwt.Auth) (string, error)) *MockJwtToken_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockJwtToken
func (_mock *MockJwtToken) Validate(jwtToken string) (*jwt.Auth, error) {
	ret := _mock.Called(jwtToken)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *jwt.Auth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*jwt.Auth, error)); ok {
		return returnFunc(jwtToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *jwt.Auth); ok {
		r0 = returnFunc(jwtToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Auth)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(jwtToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwtToken_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockJwtToken_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - jwtToken string
func (_e *MockJwtToken_Expecter) Validate(jwtToken any) *MockJwtToken_Validate_Call {
	return &MockJwtToken_Validate_Call{Call: _e.mock.On("Validate", jwtToken)}
}

func (_c *MockJwtToken_Validate_Call) Run(run func(jwtToken string)) *MockJwtToken_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJwtToken_Validate_Call) Return(auth *jwt.Auth, err error) *MockJwtToken_Validate_Call {
	_c.Call.Return(auth, err)
	return _c
}

func (_c *MockJwtToken_Validate_Call) RunAndReturn(run func(jwtToken string) (*jwt.Auth, error)) *MockJwtToken_Validate_Call {
	_c.Call.Return(run)
	return _c
}
