// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Mpayy/e-commerce/pkg/jwt"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJwtToken creates a new instance of MockJwtToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwtToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwtToken {
	mock := &MockJwtToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwtToken is an autogenerated mock type for the JwtToken type
type MockJwtToken struct {
	mock.Mock
}

type MockJwtToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwtToken) EXPECT() *MockJwtToken_Expecter {
	return &MockJwtToken_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function for the type MockJwtToken
func (_mock *MockJwtToken) CreateToken(auth *jwt.Auth) (string, error) {
	ret := _mock.Called(auth)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*jwt.Auth) (string, error)); ok {
		return returnFunc(auth)
	}
	if returnFunc, ok := ret.Get(0).(func(*jwt.Auth) string); ok {
		r0 = returnFunc(auth)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*jwt.Auth) error); ok {
		r1 = returnFunc(auth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwtToken_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockJwtToken_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - auth *jwt.Auth
func (_e *MockJwtToken_Expecter) CreateToken(auth any) *MockJwtToken_CreateToken_Call {
	return &MockJwtToken_CreateToken_Call{Call: _e.mock.On("CreateToken", auth)}
}

func (_c *MockJwtToken_CreateToken_Call) Run(run func(auth *jwt.Auth)) *MockJwtToken_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *jwt.Auth
		if args[0] != nil {
			arg0 = args[0].(*jwt.Auth)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJwtToken_CreateToken_Call) Return(s string, err error) *MockJwtToken_CreateToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJwtToken_CreateToken_Call) RunAndReturn(run func(auth *jwt.Auth) (string, error)) *MockJwtToken_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToken provides a mock function for the type MockJwtToken
func (_mock *MockJwtToken) ParseToken(token string) (*jwt.Auth, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 *jwt.Auth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*jwt.Auth, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *jwt.Auth); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Auth)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwtToken_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type MockJwtToken_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - token string
func (_e *MockJwtToken_Expecter) ParseToken(token any) *MockJwtToken_ParseToken_Call {
	return &MockJwtToken_ParseToken_Call{Call: _e.mock.On("ParseToken", token)}
}

func (_c *MockJwtToken_ParseToken_Call) Run(run func(token string)) *MockJwtToken_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJwtToken_ParseToken_Call) Return(auth *jwt.Auth, err error) *MockJwtToken_ParseToken_Call {
	_c.Call.Return(auth, err)
	return _c
}

func (_c *MockJwtToken_ParseToken_Call) RunAndReturn(run func(token string) (*jwt.Auth, error)) *MockJwtToken_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}
