// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mpayy/e-commerce/dependency"
	"github.com/Mpayy/e-commerce/internal/cart/delivery/http"
	"github.com/Mpayy/e-commerce/internal/cart/repository"
	"github.com/Mpayy/e-commerce/internal/cart/usecase"
	"github.com/Mpayy/e-commerce/internal/middleware"
	"github.com/Mpayy/e-commerce/internal/product/delivery/http"
	"github.com/Mpayy/e-commerce/internal/product/repository"
	"github.com/Mpayy/e-commerce/internal/product/usecase"
	"github.com/Mpayy/e-commerce/internal/user/delivery/http"
	"github.com/Mpayy/e-commerce/internal/user/repository"
	"github.com/Mpayy/e-commerce/internal/user/usecase"
	"github.com/Mpayy/e-commerce/pkg/jwt"
	"github.com/Mpayy/e-commerce/pkg/transaction"
	"github.com/Mpayy/e-commerce/routes"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeApplication() *Application {
	viper := dependency.NewViper()
	logger := dependency.NewLogrus(viper)
	engine := dependency.NewGin(viper, logger)
	db := dependency.NewGorm(viper, logger)
	app := dependency.NewApp(engine, logger, viper, db)
	jwtToken := jwt.NewJwtToken(viper)
	client := dependency.NewRedisClient(viper)
	redis := dependency.NewRedis(client)
	authMiddleware := middleware.NewAuthMiddleware(jwtToken, redis)
	adminMiddleware := middleware.NewAdminMiddleware()
	userRepository := userrepository.NewUserRepository(db)
	transactionTransaction := transaction.NewTransaction(db)
	userUsecase := userusecase.NewUserUsecase(userRepository, redis, transactionTransaction, logger, jwtToken)
	validate := dependency.NewValidator()
	userHandler := userhttp.NewUserHandler(userUsecase, validate, logger)
	categoryRepository := productrepository.NewCategoryRepository(db)
	categoryUsecase := productusecase.NewCategoryUsecase(categoryRepository, logger, transactionTransaction)
	categoryHandler := producthttp.NewCategoryHandler(categoryUsecase, validate, logger)
	productRepository := productrepository.NewProductRepository(db)
	productUsecaseImpl := productusecase.NewProductUsecase(productRepository, categoryUsecase, logger, transactionTransaction)
	productHandler := producthttp.NewProductHandler(productUsecaseImpl, validate, logger)
	cartRedisRepository := cartrepository.NewCartRedisRepository(client)
	cartUsecase := cartusecase.NewCartUsecase(cartRedisRepository, productUsecaseImpl, logger)
	cartHandler := carthttp.NewCartHandler(cartUsecase, validate, logger)
	router := routes.NewRouter(engine, authMiddleware, adminMiddleware, userHandler, categoryHandler, productHandler, cartHandler, logger)
	application := NewApplication(app, router)
	return application
}

// injector.go:

var userSet = wire.NewSet(userrepository.NewUserRepository, userusecase.NewUserUsecase, userhttp.NewUserHandler)

var categorySet = wire.NewSet(productrepository.NewCategoryRepository, productusecase.NewCategoryUsecase, producthttp.NewCategoryHandler)

var productSet = wire.NewSet(productrepository.NewProductRepository, productusecase.NewProductUsecase, wire.Bind(new(productusecase.ProductService), new(*productusecase.ProductUsecaseImpl)), wire.Bind(new(productusecase.ProductUsecase), new(*productusecase.ProductUsecaseImpl)), producthttp.NewProductHandler)

var cartSet = wire.NewSet(cartrepository.NewCartRedisRepository, cartusecase.NewCartUsecase, carthttp.NewCartHandler)

var middlewareSet = wire.NewSet(middleware.NewAuthMiddleware, middleware.NewAdminMiddleware)

var routeSet = wire.NewSet(routes.NewRouter)
