// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mpayy/e-commerce/dependency"
	"github.com/Mpayy/e-commerce/internal/middleware"
	"github.com/Mpayy/e-commerce/internal/user/delivery/http"
	"github.com/Mpayy/e-commerce/internal/user/repository"
	"github.com/Mpayy/e-commerce/internal/user/usecase"
	"github.com/Mpayy/e-commerce/pkg/jwt"
	"github.com/Mpayy/e-commerce/pkg/transaction"
	"github.com/Mpayy/e-commerce/routes"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeApplication() *Application {
	viper := dependency.NewViper()
	logger := dependency.NewLogrus(viper)
	engine := dependency.NewGin(viper, logger)
	db := dependency.NewGorm(viper, logger)
	app := dependency.NewApp(engine, logger, viper, db)
	jwtToken := jwt.NewJwtToken(viper)
	redis := dependency.NewRedis(viper)
	authMiddleware := middleware.NewAuthMiddleware(jwtToken, redis)
	userRepository := repository.NewUserRepository(db)
	transactionTransaction := transaction.NewTransaction(db)
	userUsecase := usecase.NewUserUsecase(userRepository, redis, transactionTransaction, logger, jwtToken)
	validate := dependency.NewValidator()
	userHandler := http.NewUserHandler(userUsecase, validate, logger)
	router := routes.NewRouter(engine, authMiddleware, userHandler, logger)
	application := NewApplication(app, router)
	return application
}

// injector.go:

var userSet = wire.NewSet(repository.NewUserRepository, usecase.NewUserUsecase, http.NewUserHandler)

var middlewareSet = wire.NewSet(middleware.NewAuthMiddleware)

var routeSet = wire.NewSet(routes.NewRouter)
