// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mpayy/e-commerce/dependency"
	"github.com/Mpayy/e-commerce/internal/cart/delivery/http"
	repository3 "github.com/Mpayy/e-commerce/internal/cart/repository"
	usecase2 "github.com/Mpayy/e-commerce/internal/cart/usecase"
	"github.com/Mpayy/e-commerce/internal/middleware"
	"github.com/Mpayy/e-commerce/internal/order/delivery/http"
	repository2 "github.com/Mpayy/e-commerce/internal/order/repository"
	usecase3 "github.com/Mpayy/e-commerce/internal/order/usecase"
	"github.com/Mpayy/e-commerce/internal/product/delivery/http"
	"github.com/Mpayy/e-commerce/internal/product/repository"
	"github.com/Mpayy/e-commerce/internal/product/usecase"
	"github.com/Mpayy/e-commerce/internal/user/delivery/http"
	"github.com/Mpayy/e-commerce/internal/user/repository"
	"github.com/Mpayy/e-commerce/internal/user/usecase"
	"github.com/Mpayy/e-commerce/pkg/jwt"
	"github.com/Mpayy/e-commerce/pkg/transaction"
	"github.com/Mpayy/e-commerce/routes"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeApplication() *Application {
	viper := dependency.NewViper()
	logger := dependency.NewLogrus(viper)
	engine := dependency.NewGin(viper, logger)
	db := dependency.NewGorm(viper, logger)
	app := dependency.NewApp(engine, logger, viper, db)
	jwtToken := jwt.NewJwtToken(viper)
	client := dependency.NewRedisClient(viper)
	redis := dependency.NewRedis(client)
	authMiddleware := middleware.NewAuthMiddleware(jwtToken, redis)
	adminMiddleware := middleware.NewAdminMiddleware()
	userRepository := userrepository.NewUserRepository(db)
	transactionTransaction := transaction.NewTransaction(db)
	userUsecase := userusecase.NewUserUsecase(userRepository, redis, transactionTransaction, logger, jwtToken)
	validate := dependency.NewValidator()
	userHandler := userhttp.NewUserHandler(userUsecase, validate, logger)
	categoryRepository := repository.NewCategoryRepository(db)
	categoryUsecase := usecase.NewCategoryUsecase(categoryRepository, logger, transactionTransaction)
	categoryHandler := producthttp.NewCategoryHandler(categoryUsecase, validate, logger)
	productRepository := repository.NewProductRepository(db)
	productUsecaseImpl := usecase.NewProductUsecase(productRepository, categoryUsecase, logger, transactionTransaction)
	productHandler := producthttp.NewProductHandler(productUsecaseImpl, validate, logger)
	orderRepository := repository2.NewOrderRepository(db)
	cartRedisRepository := repository3.NewCartRedisRepository(client)
	cartUsecaseImpl := usecase2.NewCartUsecase(cartRedisRepository, productUsecaseImpl, logger)
	orderUsecase := usecase3.NewOrderUsecase(orderRepository, transactionTransaction, logger, cartUsecaseImpl, productUsecaseImpl)
	orderHandler := orderhttp.NewOrderHandler(orderUsecase, logger)
	cartHandler := carthttp.NewCartHandler(cartUsecaseImpl, cartUsecaseImpl, validate, logger)
	router := routes.NewRouter(engine, authMiddleware, adminMiddleware, userHandler, categoryHandler, productHandler, orderHandler, cartHandler, logger)
	application := NewApplication(app, router)
	return application
}

// injector.go:

var userSet = wire.NewSet(userrepository.NewUserRepository, userusecase.NewUserUsecase, userhttp.NewUserHandler)

var categorySet = wire.NewSet(repository.NewCategoryRepository, usecase.NewCategoryUsecase, producthttp.NewCategoryHandler)

var productSet = wire.NewSet(repository.NewProductRepository, usecase.NewProductUsecase, wire.Bind(new(usecase.ProductService), new(*usecase.ProductUsecaseImpl)), wire.Bind(new(usecase.ProductUsecase), new(*usecase.ProductUsecaseImpl)), producthttp.NewProductHandler)

var cartSet = wire.NewSet(repository3.NewCartRedisRepository, usecase2.NewCartUsecase, wire.Bind(new(usecase2.CartService), new(*usecase2.CartUsecaseImpl)), wire.Bind(new(usecase2.CartUsecase), new(*usecase2.CartUsecaseImpl)), carthttp.NewCartHandler)

var orderSet = wire.NewSet(repository2.NewOrderRepository, usecase3.NewOrderUsecase, orderhttp.NewOrderHandler)

var middlewareSet = wire.NewSet(middleware.NewAuthMiddleware, middleware.NewAdminMiddleware)

var routeSet = wire.NewSet(routes.NewRouter)
