// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID            int64
	UserID        int64
	InvoiceNumber pgtype.Text
	TotalAmount   float64
	Status        string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type OrderItem struct {
	ID          int64
	OrderID     int64
	ProductID   int64
	ProductName string
	Price       float64
	Quantity    int32
	Subtotal    float64
}
