// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET status = 'CANCELLED', updated_at = NOW()
WHERE id = $1 AND status = 'PAID'
RETURNING id, invoice_number, status
`

type CancelOrderRow struct {
	ID            int64
	InvoiceNumber pgtype.Text
	Status        string
}

func (q *Queries) CancelOrder(ctx context.Context, orderID int64) (CancelOrderRow, error) {
	row := q.db.QueryRow(ctx, cancelOrder, orderID)
	var i CancelOrderRow
	err := row.Scan(&i.ID, &i.InvoiceNumber, &i.Status)
	return i, err
}

const countOrdersByUser = `-- name: CountOrdersByUser :one
SELECT COUNT(*)::BIGINT
FROM orders
WHERE user_id = $1
`

func (q *Queries) CountOrdersByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, total_amount, status, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, user_id, invoice_number, total_amount, status, created_at, updated_at
`

type CreateOrderParams struct {
	UserID      int64
	TotalAmount float64
	Status      string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.TotalAmount, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvoiceNumber,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyRevenueReport = `-- name: GetDailyRevenueReport :many
WITH daily_summary AS (
    SELECT
    DATE(created_at) AS date,
    COUNT(*)::BIGINT AS order_count,
    SUM(total_amount)::NUMERIC AS daily_revenue
    FROM orders
    WHERE status = 'PAID'
      AND created_at >= $1::TIMESTAMP 
      AND created_at <= $2::TIMESTAMP
    GROUP BY DATE(created_at)
)
SELECT
date, 
order_count,
daily_revenue,
SUM(daily_revenue) OVER (ORDER BY date ASC)::NUMERIC AS running_total
FROM daily_summary
ORDER BY date ASC
`

type GetDailyRevenueReportParams struct {
	FromDate time.Time
	ToDate   time.Time
}

type GetDailyRevenueReportRow struct {
	Date         time.Time
	OrderCount   int64
	DailyRevenue float64
	RunningTotal float64
}

func (q *Queries) GetDailyRevenueReport(ctx context.Context, arg GetDailyRevenueReportParams) ([]GetDailyRevenueReportRow, error) {
	rows, err := q.db.Query(ctx, getDailyRevenueReport, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyRevenueReportRow
	for rows.Next() {
		var i GetDailyRevenueReportRow
		if err := rows.Scan(
			&i.Date,
			&i.OrderCount,
			&i.DailyRevenue,
			&i.RunningTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, invoice_number, total_amount, status, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvoiceNumber,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, invoice_number, total_amount, status, created_at, updated_at FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InvoiceNumber,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceNumber = `-- name: UpdateInvoiceNumber :exec
UPDATE orders
SET invoice_number = $2
WHERE id = $1
`

type UpdateInvoiceNumberParams struct {
	ID            int64
	InvoiceNumber pgtype.Text
}

func (q *Queries) UpdateInvoiceNumber(ctx context.Context, arg UpdateInvoiceNumberParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceNumber, arg.ID, arg.InvoiceNumber)
	return err
}
