// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_item.sql

package sqlc

import (
	"context"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, product_name, price, quantity, subtotal)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, product_id, product_name, price, quantity, subtotal
`

type CreateOrderItemParams struct {
	OrderID     int64
	ProductID   int64
	ProductName string
	Price       float64
	Quantity    int32
	Subtotal    float64
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.Price,
		arg.Quantity,
		arg.Subtotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductName,
		&i.Price,
		&i.Quantity,
		&i.Subtotal,
	)
	return i, err
}

const getItemsByOrderID = `-- name: GetItemsByOrderID :many
SELECT id, order_id, product_id, product_name, price, quantity, subtotal
FROM order_items
WHERE order_id = $1
`

func (q *Queries) GetItemsByOrderID(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductName,
			&i.Price,
			&i.Quantity,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByOrderIDs = `-- name: ListItemsByOrderIDs :many
SELECT id, order_id, product_id, product_name, price, quantity, subtotal
FROM order_items
WHERE order_id = ANY($1::bigint[])
`

func (q *Queries) ListItemsByOrderIDs(ctx context.Context, orderIds []int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listItemsByOrderIDs, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductName,
			&i.Price,
			&i.Quantity,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
