// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrdersByUser = `-- name: CountOrdersByUser :one
SELECT COUNT(*)
FROM orders
WHERE user_id = $1
`

func (q *Queries) CountOrdersByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, total_amount, status, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, user_id, invoice_number, total_amount, status, created_at, updated_at
`

type CreateOrderParams struct {
	UserID      int64
	TotalAmount float64
	Status      string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.TotalAmount, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvoiceNumber,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, invoice_number, total_amount, status, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvoiceNumber,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, invoice_number, total_amount, status, created_at, updated_at FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InvoiceNumber,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceNumber = `-- name: UpdateInvoiceNumber :exec
UPDATE orders
SET invoice_number = $2
WHERE id = $1
`

type UpdateInvoiceNumberParams struct {
	ID            int64
	InvoiceNumber pgtype.Text
}

func (q *Queries) UpdateInvoiceNumber(ctx context.Context, arg UpdateInvoiceNumberParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceNumber, arg.ID, arg.InvoiceNumber)
	return err
}
