// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/product/v1/product.proto

package productv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	Sku           string                 `protobuf:"bytes,8,opt,name=sku,proto3" json:"sku,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_proto_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDsRequest) Reset() {
	*x = GetByIDsRequest{}
	mi := &file_proto_product_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDsRequest) ProtoMessage() {}

func (x *GetByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *GetByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDResponse) Reset() {
	*x = GetByIDResponse{}
	mi := &file_proto_product_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDResponse) ProtoMessage() {}

func (x *GetByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDResponse.ProtoReflect.Descriptor instead.
func (*GetByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetByIDResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDsResponse) Reset() {
	*x = GetByIDsResponse{}
	mi := &file_proto_product_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDsResponse) ProtoMessage() {}

func (x *GetByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetByIDsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type DecreaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseStockRequest) Reset() {
	*x = DecreaseStockRequest{}
	mi := &file_proto_product_v1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseStockRequest) ProtoMessage() {}

func (x *DecreaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseStockRequest.ProtoReflect.Descriptor instead.
func (*DecreaseStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_proto_rawDescGZIP(), []int{5}
}

func (x *DecreaseStockRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DecreaseStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BulkDecreaseStockRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CheckoutId    string                  `protobuf:"bytes,1,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	Items         []*DecreaseStockRequest `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkDecreaseStockRequest) Reset() {
	*x = BulkDecreaseStockRequest{}
	mi := &file_proto_product_v1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkDecreaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkDecreaseStockRequest) ProtoMessage() {}

func (x *BulkDecreaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkDecreaseStockRequest.ProtoReflect.Descriptor instead.
func (*BulkDecreaseStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_proto_rawDescGZIP(), []int{6}
}

func (x *BulkDecreaseStockRequest) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *BulkDecreaseStockRequest) GetItems() []*DecreaseStockRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type BulkDecreaseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkDecreaseStockResponse) Reset() {
	*x = BulkDecreaseStockResponse{}
	mi := &file_proto_product_v1_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkDecreaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkDecreaseStockResponse) ProtoMessage() {}

func (x *BulkDecreaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkDecreaseStockResponse.ProtoReflect.Descriptor instead.
func (*BulkDecreaseStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_proto_rawDescGZIP(), []int{7}
}

type BulkRestoreStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutId    string                 `protobuf:"bytes,1,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRestoreStockRequest) Reset() {
	*x = BulkRestoreStockRequest{}
	mi := &file_proto_product_v1_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRestoreStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRestoreStockRequest) ProtoMessage() {}

func (x *BulkRestoreStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRestoreStockRequest.ProtoReflect.Descriptor instead.
func (*BulkRestoreStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_proto_rawDescGZIP(), []int{8}
}

func (x *BulkRestoreStockRequest) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

type BulkRestoreStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRestoreStockResponse) Reset() {
	*x = BulkRestoreStockResponse{}
	mi := &file_proto_product_v1_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRestoreStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRestoreStockResponse) ProtoMessage() {}

func (x *BulkRestoreStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRestoreStockResponse.ProtoReflect.Descriptor instead.
func (*BulkRestoreStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_proto_rawDescGZIP(), []int{9}
}

var File_proto_product_v1_product_proto protoreflect.FileDescriptor

const file_proto_product_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/product/v1/product.proto\x12\n" +
	"product.v1\"\xdf\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x04R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x10\n" +
	"\x03sku\x18\b \x01(\tR\x03sku\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"#\n" +
	"\x0fGetByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"@\n" +
	"\x0fGetByIDResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"C\n" +
	"\x10GetByIDsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\"Q\n" +
	"\x14DecreaseStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"s\n" +
	"\x18BulkDecreaseStockRequest\x12\x1f\n" +
	"\vcheckout_id\x18\x01 \x01(\tR\n" +
	"checkoutId\x126\n" +
	"\x05items\x18\x02 \x03(\v2 .product.v1.DecreaseStockRequestR\x05items\"\x1b\n" +
	"\x19BulkDecreaseStockResponse\":\n" +
	"\x17BulkRestoreStockRequest\x12\x1f\n" +
	"\vcheckout_id\x18\x01 \x01(\tR\n" +
	"checkoutId\"\x1a\n" +
	"\x18BulkRestoreStockResponse2\xdc\x02\n" +
	"\x0eProductService\x12B\n" +
	"\aGetByID\x12\x1a.product.v1.GetByIDRequest\x1a\x1b.product.v1.GetByIDResponse\x12E\n" +
	"\bGetByIDs\x12\x1b.product.v1.GetByIDsRequest\x1a\x1c.product.v1.GetByIDsResponse\x12`\n" +
	"\x11BulkDecreaseStock\x12$.product.v1.BulkDecreaseStockRequest\x1a%.product.v1.BulkDecreaseStockResponse\x12]\n" +
	"\x10BulkRestoreStock\x12#.product.v1.BulkRestoreStockRequest\x1a$.product.v1.BulkRestoreStockResponseB8Z6github.com/Mpayy/e-commerce/proto/product/v1;productv1b\x06proto3"

var (
	file_proto_product_v1_product_proto_rawDescOnce sync.Once
	file_proto_product_v1_product_proto_rawDescData []byte
)

func file_proto_product_v1_product_proto_rawDescGZIP() []byte {
	file_proto_product_v1_product_proto_rawDescOnce.Do(func() {
		file_proto_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_v1_product_proto_rawDesc), len(file_proto_product_v1_product_proto_rawDesc)))
	})
	return file_proto_product_v1_product_proto_rawDescData
}

var file_proto_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_product_v1_product_proto_goTypes = []any{
	(*Product)(nil),                   // 0: product.v1.Product
	(*GetByIDRequest)(nil),            // 1: product.v1.GetByIDRequest
	(*GetByIDsRequest)(nil),           // 2: product.v1.GetByIDsRequest
	(*GetByIDResponse)(nil),           // 3: product.v1.GetByIDResponse
	(*GetByIDsResponse)(nil),          // 4: product.v1.GetByIDsResponse
	(*DecreaseStockRequest)(nil),      // 5: product.v1.DecreaseStockRequest
	(*BulkDecreaseStockRequest)(nil),  // 6: product.v1.BulkDecreaseStockRequest
	(*BulkDecreaseStockResponse)(nil), // 7: product.v1.BulkDecreaseStockResponse
	(*BulkRestoreStockRequest)(nil),   // 8: product.v1.BulkRestoreStockRequest
	(*BulkRestoreStockResponse)(nil),  // 9: product.v1.BulkRestoreStockResponse
}
var file_proto_product_v1_product_proto_depIdxs = []int32{
	0, // 0: product.v1.GetByIDResponse.product:type_name -> product.v1.Product
	0, // 1: product.v1.GetByIDsResponse.products:type_name -> product.v1.Product
	5, // 2: product.v1.BulkDecreaseStockRequest.items:type_name -> product.v1.DecreaseStockRequest
	1, // 3: product.v1.ProductService.GetByID:input_type -> product.v1.GetByIDRequest
	2, // 4: product.v1.ProductService.GetByIDs:input_type -> product.v1.GetByIDsRequest
	6, // 5: product.v1.ProductService.BulkDecreaseStock:input_type -> product.v1.BulkDecreaseStockRequest
	8, // 6: product.v1.ProductService.BulkRestoreStock:input_type -> product.v1.BulkRestoreStockRequest
	3, // 7: product.v1.ProductService.GetByID:output_type -> product.v1.GetByIDResponse
	4, // 8: product.v1.ProductService.GetByIDs:output_type -> product.v1.GetByIDsResponse
	7, // 9: product.v1.ProductService.BulkDecreaseStock:output_type -> product.v1.BulkDecreaseStockResponse
	9, // 10: product.v1.ProductService.BulkRestoreStock:output_type -> product.v1.BulkRestoreStockResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_product_v1_product_proto_init() }
func file_proto_product_v1_product_proto_init() {
	if File_proto_product_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_v1_product_proto_rawDesc), len(file_proto_product_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_v1_product_proto_goTypes,
		DependencyIndexes: file_proto_product_v1_product_proto_depIdxs,
		MessageInfos:      file_proto_product_v1_product_proto_msgTypes,
	}.Build()
	File_proto_product_v1_product_proto = out.File
	file_proto_product_v1_product_proto_goTypes = nil
	file_proto_product_v1_product_proto_depIdxs = nil
}
