// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// NewMockImageStorage creates a new instance of MockImageStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageStorage {
	mock := &MockImageStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageStorage is an autogenerated mock type for the ImageStorage type
type MockImageStorage struct {
	mock.Mock
}

type MockImageStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageStorage) EXPECT() *MockImageStorage_Expecter {
	return &MockImageStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockImageStorage
func (_mock *MockImageStorage) Delete(ctx context.Context, path string) error {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockImageStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockImageStorage_Expecter) Delete(ctx any, path any) *MockImageStorage_Delete_Call {
	return &MockImageStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, path)}
}

func (_c *MockImageStorage_Delete_Call) Run(run func(ctx context.Context, path string)) *MockImageStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageStorage_Delete_Call) Return(err error) *MockImageStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, path string) error) *MockImageStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockImageStorage
func (_mock *MockImageStorage) Save(ctx context.Context, fileHeader *multipart.FileHeader) (string, error) {
	ret := _mock.Called(ctx, fileHeader)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) (string, error)); ok {
		return returnFunc(ctx, fileHeader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) string); ok {
		r0 = returnFunc(ctx, fileHeader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader) error); ok {
		r1 = returnFunc(ctx, fileHeader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockImageStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - fileHeader *multipart.FileHeader
func (_e *MockImageStorage_Expecter) Save(ctx any, fileHeader any) *MockImageStorage_Save_Call {
	return &MockImageStorage_Save_Call{Call: _e.mock.On("Save", ctx, fileHeader)}
}

func (_c *MockImageStorage_Save_Call) Run(run func(ctx context.Context, fileHeader *multipart.FileHeader)) *MockImageStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *multipart.FileHeader
		if args[1] != nil {
			arg1 = args[1].(*multipart.FileHeader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageStorage_Save_Call) Return(path string, err error) *MockImageStorage_Save_Call {
	_c.Call.Return(path, err)
	return _c
}

func (_c *MockImageStorage_Save_Call) RunAndReturn(run func(ctx context.Context, fileHeader *multipart.FileHeader) (string, error)) *MockImageStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}
