// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCartRedisRepository creates a new instance of MockCartRedisRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartRedisRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartRedisRepository {
	mock := &MockCartRedisRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCartRedisRepository is an autogenerated mock type for the CartRedisRepository type
type MockCartRedisRepository struct {
	mock.Mock
}

type MockCartRedisRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartRedisRepository) EXPECT() *MockCartRedisRepository_Expecter {
	return &MockCartRedisRepository_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function for the type MockCartRedisRepository
func (_mock *MockCartRedisRepository) AddItem(ctx context.Context, userID uint, productID uint, quantity int) error {
	ret := _mock.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, int) error); ok {
		r0 = returnFunc(ctx, userID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartRedisRepository_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type MockCartRedisRepository_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - productID uint
//   - quantity int
func (_e *MockCartRedisRepository_Expecter) AddItem(ctx any, userID any, productID any, quantity any) *MockCartRedisRepository_AddItem_Call {
	return &MockCartRedisRepository_AddItem_Call{Call: _e.mock.On("AddItem", ctx, userID, productID, quantity)}
}

func (_c *MockCartRedisRepository_AddItem_Call) Run(run func(ctx context.Context, userID uint, productID uint, quantity int)) *MockCartRedisRepository_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCartRedisRepository_AddItem_Call) Return(err error) *MockCartRedisRepository_AddItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartRedisRepository_AddItem_Call) RunAndReturn(run func(ctx context.Context, userID uint, productID uint, quantity int) error) *MockCartRedisRepository_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// ClearCart provides a mock function for the type MockCartRedisRepository
func (_mock *MockCartRedisRepository) ClearCart(ctx context.Context, userID uint) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearCart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartRedisRepository_ClearCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCart'
type MockCartRedisRepository_ClearCart_Call struct {
	*mock.Call
}

// ClearCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockCartRedisRepository_Expecter) ClearCart(ctx any, userID any) *MockCartRedisRepository_ClearCart_Call {
	return &MockCartRedisRepository_ClearCart_Call{Call: _e.mock.On("ClearCart", ctx, userID)}
}

func (_c *MockCartRedisRepository_ClearCart_Call) Run(run func(ctx context.Context, userID uint)) *MockCartRedisRepository_ClearCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartRedisRepository_ClearCart_Call) Return(err error) *MockCartRedisRepository_ClearCart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartRedisRepository_ClearCart_Call) RunAndReturn(run func(ctx context.Context, userID uint) error) *MockCartRedisRepository_ClearCart_Call {
	_c.Call.Return(run)
	return _c
}

// GetCart provides a mock function for the type MockCartRedisRepository
func (_mock *MockCartRedisRepository) GetCart(ctx context.Context, userID uint) (map[uint]int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 map[uint]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (map[uint]int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) map[uint]int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCartRedisRepository_GetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCart'
type MockCartRedisRepository_GetCart_Call struct {
	*mock.Call
}

// GetCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockCartRedisRepository_Expecter) GetCart(ctx any, userID any) *MockCartRedisRepository_GetCart_Call {
	return &MockCartRedisRepository_GetCart_Call{Call: _e.mock.On("GetCart", ctx, userID)}
}

func (_c *MockCartRedisRepository_GetCart_Call) Run(run func(ctx context.Context, userID uint)) *MockCartRedisRepository_GetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartRedisRepository_GetCart_Call) Return(uintToInt map[uint]int, err error) *MockCartRedisRepository_GetCart_Call {
	_c.Call.Return(uintToInt, err)
	return _c
}

func (_c *MockCartRedisRepository_GetCart_Call) RunAndReturn(run func(ctx context.Context, userID uint) (map[uint]int, error)) *MockCartRedisRepository_GetCart_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItem provides a mock function for the type MockCartRedisRepository
func (_mock *MockCartRedisRepository) RemoveItem(ctx context.Context, userID uint, productID uint) error {
	ret := _mock.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = returnFunc(ctx, userID, productID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartRedisRepository_RemoveItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItem'
type MockCartRedisRepository_RemoveItem_Call struct {
	*mock.Call
}

// RemoveItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - productID uint
func (_e *MockCartRedisRepository_Expecter) RemoveItem(ctx any, userID any, productID any) *MockCartRedisRepository_RemoveItem_Call {
	return &MockCartRedisRepository_RemoveItem_Call{Call: _e.mock.On("RemoveItem", ctx, userID, productID)}
}

func (_c *MockCartRedisRepository_RemoveItem_Call) Run(run func(ctx context.Context, userID uint, productID uint)) *MockCartRedisRepository_RemoveItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCartRedisRepository_RemoveItem_Call) Return(err error) *MockCartRedisRepository_RemoveItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartRedisRepository_RemoveItem_Call) RunAndReturn(run func(ctx context.Context, userID uint, productID uint) error) *MockCartRedisRepository_RemoveItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type MockCartRedisRepository
func (_mock *MockCartRedisRepository) UpdateItem(ctx context.Context, userID uint, productID uint, quantity int) error {
	ret := _mock.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, int) error); ok {
		r0 = returnFunc(ctx, userID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartRedisRepository_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockCartRedisRepository_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - productID uint
//   - quantity int
func (_e *MockCartRedisRepository_Expecter) UpdateItem(ctx any, userID any, productID any, quantity any) *MockCartRedisRepository_UpdateItem_Call {
	return &MockCartRedisRepository_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, userID, productID, quantity)}
}

func (_c *MockCartRedisRepository_UpdateItem_Call) Run(run func(ctx context.Context, userID uint, productID uint, quantity int)) *MockCartRedisRepository_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCartRedisRepository_UpdateItem_Call) Return(err error) *MockCartRedisRepository_UpdateItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartRedisRepository_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, userID uint, productID uint, quantity int) error) *MockCartRedisRepository_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
