// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/e-commerce/services/order-service/internal/cart/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCartUsecase creates a new instance of MockCartUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartUsecase {
	mock := &MockCartUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCartUsecase is an autogenerated mock type for the CartUsecase type
type MockCartUsecase struct {
	mock.Mock
}

type MockCartUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartUsecase) EXPECT() *MockCartUsecase_Expecter {
	return &MockCartUsecase_Expecter{mock: &_m.Mock}
}

// AddToCart provides a mock function for the type MockCartUsecase
func (_mock *MockCartUsecase) AddToCart(ctx context.Context, userID uint, productID uint, quantity int) error {
	ret := _mock.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddToCart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, int) error); ok {
		r0 = returnFunc(ctx, userID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartUsecase_AddToCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToCart'
type MockCartUsecase_AddToCart_Call struct {
	*mock.Call
}

// AddToCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - productID uint
//   - quantity int
func (_e *MockCartUsecase_Expecter) AddToCart(ctx any, userID any, productID any, quantity any) *MockCartUsecase_AddToCart_Call {
	return &MockCartUsecase_AddToCart_Call{Call: _e.mock.On("AddToCart", ctx, userID, productID, quantity)}
}

func (_c *MockCartUsecase_AddToCart_Call) Run(run func(ctx context.Context, userID uint, productID uint, quantity int)) *MockCartUsecase_AddToCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCartUsecase_AddToCart_Call) Return(err error) *MockCartUsecase_AddToCart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartUsecase_AddToCart_Call) RunAndReturn(run func(ctx context.Context, userID uint, productID uint, quantity int) error) *MockCartUsecase_AddToCart_Call {
	_c.Call.Return(run)
	return _c
}

// GetCartDetail provides a mock function for the type MockCartUsecase
func (_mock *MockCartUsecase) GetCartDetail(ctx context.Context, userID uint) (*dto.CartDetailResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCartDetail")
	}

	var r0 *dto.CartDetailResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*dto.CartDetailResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *dto.CartDetailResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CartDetailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCartUsecase_GetCartDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCartDetail'
type MockCartUsecase_GetCartDetail_Call struct {
	*mock.Call
}

// GetCartDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockCartUsecase_Expecter) GetCartDetail(ctx any, userID any) *MockCartUsecase_GetCartDetail_Call {
	return &MockCartUsecase_GetCartDetail_Call{Call: _e.mock.On("GetCartDetail", ctx, userID)}
}

func (_c *MockCartUsecase_GetCartDetail_Call) Run(run func(ctx context.Context, userID uint)) *MockCartUsecase_GetCartDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartUsecase_GetCartDetail_Call) Return(cartDetailResponse *dto.CartDetailResponse, err error) *MockCartUsecase_GetCartDetail_Call {
	_c.Call.Return(cartDetailResponse, err)
	return _c
}

func (_c *MockCartUsecase_GetCartDetail_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*dto.CartDetailResponse, error)) *MockCartUsecase_GetCartDetail_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromCart provides a mock function for the type MockCartUsecase
func (_mock *MockCartUsecase) RemoveFromCart(ctx context.Context, userID uint, productID uint) error {
	ret := _mock.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromCart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = returnFunc(ctx, userID, productID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartUsecase_RemoveFromCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromCart'
type MockCartUsecase_RemoveFromCart_Call struct {
	*mock.Call
}

// RemoveFromCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - productID uint
func (_e *MockCartUsecase_Expecter) RemoveFromCart(ctx any, userID any, productID any) *MockCartUsecase_RemoveFromCart_Call {
	return &MockCartUsecase_RemoveFromCart_Call{Call: _e.mock.On("RemoveFromCart", ctx, userID, productID)}
}

func (_c *MockCartUsecase_RemoveFromCart_Call) Run(run func(ctx context.Context, userID uint, productID uint)) *MockCartUsecase_RemoveFromCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCartUsecase_RemoveFromCart_Call) Return(err error) *MockCartUsecase_RemoveFromCart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartUsecase_RemoveFromCart_Call) RunAndReturn(run func(ctx context.Context, userID uint, productID uint) error) *MockCartUsecase_RemoveFromCart_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCartItem provides a mock function for the type MockCartUsecase
func (_mock *MockCartUsecase) UpdateCartItem(ctx context.Context, userID uint, productID uint, quantity int) error {
	ret := _mock.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCartItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, int) error); ok {
		r0 = returnFunc(ctx, userID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartUsecase_UpdateCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCartItem'
type MockCartUsecase_UpdateCartItem_Call struct {
	*mock.Call
}

// UpdateCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - productID uint
//   - quantity int
func (_e *MockCartUsecase_Expecter) UpdateCartItem(ctx any, userID any, productID any, quantity any) *MockCartUsecase_UpdateCartItem_Call {
	return &MockCartUsecase_UpdateCartItem_Call{Call: _e.mock.On("UpdateCartItem", ctx, userID, productID, quantity)}
}

func (_c *MockCartUsecase_UpdateCartItem_Call) Run(run func(ctx context.Context, userID uint, productID uint, quantity int)) *MockCartUsecase_UpdateCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCartUsecase_UpdateCartItem_Call) Return(err error) *MockCartUsecase_UpdateCartItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartUsecase_UpdateCartItem_Call) RunAndReturn(run func(ctx context.Context, userID uint, productID uint, quantity int) error) *MockCartUsecase_UpdateCartItem_Call {
	_c.Call.Return(run)
	return _c
}
