// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/e-commerce/services/order-service/internal/order/event"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishOrderCreated provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) PublishOrderCreated(ctx context.Context, event1 event.OrderCreatedEvent) error {
	ret := _mock.Called(ctx, event1)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.OrderCreatedEvent) error); ok {
		r0 = returnFunc(ctx, event1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_PublishOrderCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOrderCreated'
type MockEventPublisher_PublishOrderCreated_Call struct {
	*mock.Call
}

// PublishOrderCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - event1 event.OrderCreatedEvent
func (_e *MockEventPublisher_Expecter) PublishOrderCreated(ctx any, event1 any) *MockEventPublisher_PublishOrderCreated_Call {
	return &MockEventPublisher_PublishOrderCreated_Call{Call: _e.mock.On("PublishOrderCreated", ctx, event1)}
}

func (_c *MockEventPublisher_PublishOrderCreated_Call) Run(run func(ctx context.Context, event1 event.OrderCreatedEvent)) *MockEventPublisher_PublishOrderCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 event.OrderCreatedEvent
		if args[1] != nil {
			arg1 = args[1].(event.OrderCreatedEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventPublisher_PublishOrderCreated_Call) Return(err error) *MockEventPublisher_PublishOrderCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_PublishOrderCreated_Call) RunAndReturn(run func(ctx context.Context, event1 event.OrderCreatedEvent) error) *MockEventPublisher_PublishOrderCreated_Call {
	_c.Call.Return(run)
	return _c
}
