// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Mpayy/e-commerce/services/order-service/internal/order/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// CountAdminOrderList provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) CountAdminOrderList(ctx context.Context, filter *entity.OrderFilter) (int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for CountAdminOrderList")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.OrderFilter) (int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.OrderFilter) int64); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.OrderFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_CountAdminOrderList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAdminOrderList'
type MockOrderRepository_CountAdminOrderList_Call struct {
	*mock.Call
}

// CountAdminOrderList is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *entity.OrderFilter
func (_e *MockOrderRepository_Expecter) CountAdminOrderList(ctx any, filter any) *MockOrderRepository_CountAdminOrderList_Call {
	return &MockOrderRepository_CountAdminOrderList_Call{Call: _e.mock.On("CountAdminOrderList", ctx, filter)}
}

func (_c *MockOrderRepository_CountAdminOrderList_Call) Run(run func(ctx context.Context, filter *entity.OrderFilter)) *MockOrderRepository_CountAdminOrderList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.OrderFilter
		if args[1] != nil {
			arg1 = args[1].(*entity.OrderFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_CountAdminOrderList_Call) Return(n int64, err error) *MockOrderRepository_CountAdminOrderList_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOrderRepository_CountAdminOrderList_Call) RunAndReturn(run func(ctx context.Context, filter *entity.OrderFilter) (int64, error)) *MockOrderRepository_CountAdminOrderList_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrderWithItems provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) CreateOrderWithItems(ctx context.Context, order *entity.Order, items []entity.OrderItem) error {
	ret := _mock.Called(ctx, order, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrderWithItems")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Order, []entity.OrderItem) error); ok {
		r0 = returnFunc(ctx, order, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_CreateOrderWithItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrderWithItems'
type MockOrderRepository_CreateOrderWithItems_Call struct {
	*mock.Call
}

// CreateOrderWithItems is a helper method to define mock.On call
//   - ctx context.Context
//   - order *entity.Order
//   - items []entity.OrderItem
func (_e *MockOrderRepository_Expecter) CreateOrderWithItems(ctx any, order any, items any) *MockOrderRepository_CreateOrderWithItems_Call {
	return &MockOrderRepository_CreateOrderWithItems_Call{Call: _e.mock.On("CreateOrderWithItems", ctx, order, items)}
}

func (_c *MockOrderRepository_CreateOrderWithItems_Call) Run(run func(ctx context.Context, order *entity.Order, items []entity.OrderItem)) *MockOrderRepository_CreateOrderWithItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Order
		if args[1] != nil {
			arg1 = args[1].(*entity.Order)
		}
		var arg2 []entity.OrderItem
		if args[2] != nil {
			arg2 = args[2].([]entity.OrderItem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepository_CreateOrderWithItems_Call) Return(err error) *MockOrderRepository_CreateOrderWithItems_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_CreateOrderWithItems_Call) RunAndReturn(run func(ctx context.Context, order *entity.Order, items []entity.OrderItem) error) *MockOrderRepository_CreateOrderWithItems_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) FindByID(ctx context.Context, orderID uint) (*entity.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*entity.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *entity.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockOrderRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uint
func (_e *MockOrderRepository_Expecter) FindByID(ctx any, orderID any) *MockOrderRepository_FindByID_Call {
	return &MockOrderRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, orderID)}
}

func (_c *MockOrderRepository_FindByID_Call) Run(run func(ctx context.Context, orderID uint)) *MockOrderRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_FindByID_Call) Return(order *entity.Order, err error) *MockOrderRepository_FindByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, orderID uint) (*entity.Order, error)) *MockOrderRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) FindByUserID(ctx context.Context, userID uint, page int, limit int) ([]entity.Order, int64, error) {
	ret := _mock.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []entity.Order
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, int, int) ([]entity.Order, int64, error)); ok {
		return returnFunc(ctx, userID, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, int, int) []entity.Order); ok {
		r0 = returnFunc(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, int, int) int64); ok {
		r1 = returnFunc(ctx, userID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, int, int) error); ok {
		r2 = returnFunc(ctx, userID, page, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOrderRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockOrderRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - page int
//   - limit int
func (_e *MockOrderRepository_Expecter) FindByUserID(ctx any, userID any, page any, limit any) *MockOrderRepository_FindByUserID_Call {
	return &MockOrderRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID, page, limit)}
}

func (_c *MockOrderRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID uint, page int, limit int)) *MockOrderRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderRepository_FindByUserID_Call) Return(orders []entity.Order, n int64, err error) *MockOrderRepository_FindByUserID_Call {
	_c.Call.Return(orders, n, err)
	return _c
}

func (_c *MockOrderRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint, page int, limit int) ([]entity.Order, int64, error)) *MockOrderRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAdminOrderList provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetAdminOrderList(ctx context.Context, filter *entity.OrderFilter) ([]entity.Order, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminOrderList")
	}

	var r0 []entity.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.OrderFilter) ([]entity.Order, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.OrderFilter) []entity.Order); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.OrderFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_GetAdminOrderList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAdminOrderList'
type MockOrderRepository_GetAdminOrderList_Call struct {
	*mock.Call
}

// GetAdminOrderList is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *entity.OrderFilter
func (_e *MockOrderRepository_Expecter) GetAdminOrderList(ctx any, filter any) *MockOrderRepository_GetAdminOrderList_Call {
	return &MockOrderRepository_GetAdminOrderList_Call{Call: _e.mock.On("GetAdminOrderList", ctx, filter)}
}

func (_c *MockOrderRepository_GetAdminOrderList_Call) Run(run func(ctx context.Context, filter *entity.OrderFilter)) *MockOrderRepository_GetAdminOrderList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.OrderFilter
		if args[1] != nil {
			arg1 = args[1].(*entity.OrderFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_GetAdminOrderList_Call) Return(orders []entity.Order, err error) *MockOrderRepository_GetAdminOrderList_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderRepository_GetAdminOrderList_Call) RunAndReturn(run func(ctx context.Context, filter *entity.OrderFilter) ([]entity.Order, error)) *MockOrderRepository_GetAdminOrderList_Call {
	_c.Call.Return(run)
	return _c
}

// GetDailyRevenueReport provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetDailyRevenueReport(ctx context.Context, from time.Time, to time.Time) ([]entity.DailyRevenueRow, error) {
	ret := _mock.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyRevenueReport")
	}

	var r0 []entity.DailyRevenueRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]entity.DailyRevenueRow, error)); ok {
		return returnFunc(ctx, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []entity.DailyRevenueRow); ok {
		r0 = returnFunc(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.DailyRevenueRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_GetDailyRevenueReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyRevenueReport'
type MockOrderRepository_GetDailyRevenueReport_Call struct {
	*mock.Call
}

// GetDailyRevenueReport is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
func (_e *MockOrderRepository_Expecter) GetDailyRevenueReport(ctx any, from any, to any) *MockOrderRepository_GetDailyRevenueReport_Call {
	return &MockOrderRepository_GetDailyRevenueReport_Call{Call: _e.mock.On("GetDailyRevenueReport", ctx, from, to)}
}

func (_c *MockOrderRepository_GetDailyRevenueReport_Call) Run(run func(ctx context.Context, from time.Time, to time.Time)) *MockOrderRepository_GetDailyRevenueReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepository_GetDailyRevenueReport_Call) Return(dailyRevenueRows []entity.DailyRevenueRow, err error) *MockOrderRepository_GetDailyRevenueReport_Call {
	_c.Call.Return(dailyRevenueRows, err)
	return _c
}

func (_c *MockOrderRepository_GetDailyRevenueReport_Call) RunAndReturn(run func(ctx context.Context, from time.Time, to time.Time) ([]entity.DailyRevenueRow, error)) *MockOrderRepository_GetDailyRevenueReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopProducts provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetTopProducts(ctx context.Context, from time.Time, to time.Time, limit int32) ([]entity.TopProductRow, error) {
	ret := _mock.Called(ctx, from, to, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTopProducts")
	}

	var r0 []entity.TopProductRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int32) ([]entity.TopProductRow, error)); ok {
		return returnFunc(ctx, from, to, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int32) []entity.TopProductRow); ok {
		r0 = returnFunc(ctx, from, to, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TopProductRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int32) error); ok {
		r1 = returnFunc(ctx, from, to, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_GetTopProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopProducts'
type MockOrderRepository_GetTopProducts_Call struct {
	*mock.Call
}

// GetTopProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
//   - limit int32
func (_e *MockOrderRepository_Expecter) GetTopProducts(ctx any, from any, to any, limit any) *MockOrderRepository_GetTopProducts_Call {
	return &MockOrderRepository_GetTopProducts_Call{Call: _e.mock.On("GetTopProducts", ctx, from, to, limit)}
}

func (_c *MockOrderRepository_GetTopProducts_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, limit int32)) *MockOrderRepository_GetTopProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderRepository_GetTopProducts_Call) Return(topProductRows []entity.TopProductRow, err error) *MockOrderRepository_GetTopProducts_Call {
	_c.Call.Return(topProductRows, err)
	return _c
}

func (_c *MockOrderRepository_GetTopProducts_Call) RunAndReturn(run func(ctx context.Context, from time.Time, to time.Time, limit int32) ([]entity.TopProductRow, error)) *MockOrderRepository_GetTopProducts_Call {
	_c.Call.Return(run)
	return _c
}
