// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Mpayy/e-commerce/services/order-service/internal/order/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIdempotencyRepository creates a new instance of MockIdempotencyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdempotencyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdempotencyRepository {
	mock := &MockIdempotencyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdempotencyRepository is an autogenerated mock type for the IdempotencyRepository type
type MockIdempotencyRepository struct {
	mock.Mock
}

type MockIdempotencyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdempotencyRepository) EXPECT() *MockIdempotencyRepository_Expecter {
	return &MockIdempotencyRepository_Expecter{mock: &_m.Mock}
}

// GetResponse provides a mock function for the type MockIdempotencyRepository
func (_mock *MockIdempotencyRepository) GetResponse(ctx context.Context, idemKey string) (*dto.IdempotencyResponse, error) {
	ret := _mock.Called(ctx, idemKey)

	if len(ret) == 0 {
		panic("no return value specified for GetResponse")
	}

	var r0 *dto.IdempotencyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.IdempotencyResponse, error)); ok {
		return returnFunc(ctx, idemKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.IdempotencyResponse); ok {
		r0 = returnFunc(ctx, idemKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.IdempotencyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, idemKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdempotencyRepository_GetResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResponse'
type MockIdempotencyRepository_GetResponse_Call struct {
	*mock.Call
}

// GetResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - idemKey string
func (_e *MockIdempotencyRepository_Expecter) GetResponse(ctx any, idemKey any) *MockIdempotencyRepository_GetResponse_Call {
	return &MockIdempotencyRepository_GetResponse_Call{Call: _e.mock.On("GetResponse", ctx, idemKey)}
}

func (_c *MockIdempotencyRepository_GetResponse_Call) Run(run func(ctx context.Context, idemKey string)) *MockIdempotencyRepository_GetResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdempotencyRepository_GetResponse_Call) Return(idempotencyResponse *dto.IdempotencyResponse, err error) *MockIdempotencyRepository_GetResponse_Call {
	_c.Call.Return(idempotencyResponse, err)
	return _c
}

func (_c *MockIdempotencyRepository_GetResponse_Call) RunAndReturn(run func(ctx context.Context, idemKey string) (*dto.IdempotencyResponse, error)) *MockIdempotencyRepository_GetResponse_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function for the type MockIdempotencyRepository
func (_mock *MockIdempotencyRepository) Lock(ctx context.Context, idemKey string, lockTTL time.Duration) (bool, error) {
	ret := _mock.Called(ctx, idemKey, lockTTL)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, idemKey, lockTTL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) bool); ok {
		r0 = returnFunc(ctx, idemKey, lockTTL)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, idemKey, lockTTL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdempotencyRepository_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockIdempotencyRepository_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - ctx context.Context
//   - idemKey string
//   - lockTTL time.Duration
func (_e *MockIdempotencyRepository_Expecter) Lock(ctx any, idemKey any, lockTTL any) *MockIdempotencyRepository_Lock_Call {
	return &MockIdempotencyRepository_Lock_Call{Call: _e.mock.On("Lock", ctx, idemKey, lockTTL)}
}

func (_c *MockIdempotencyRepository_Lock_Call) Run(run func(ctx context.Context, idemKey string, lockTTL time.Duration)) *MockIdempotencyRepository_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIdempotencyRepository_Lock_Call) Return(b bool, err error) *MockIdempotencyRepository_Lock_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIdempotencyRepository_Lock_Call) RunAndReturn(run func(ctx context.Context, idemKey string, lockTTL time.Duration) (bool, error)) *MockIdempotencyRepository_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// SaveResponse provides a mock function for the type MockIdempotencyRepository
func (_mock *MockIdempotencyRepository) SaveResponse(ctx context.Context, idemKey string, statusCode int, res *dto.OrderResponse, resultTTL time.Duration) error {
	ret := _mock.Called(ctx, idemKey, statusCode, res, resultTTL)

	if len(ret) == 0 {
		panic("no return value specified for SaveResponse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, *dto.OrderResponse, time.Duration) error); ok {
		r0 = returnFunc(ctx, idemKey, statusCode, res, resultTTL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdempotencyRepository_SaveResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveResponse'
type MockIdempotencyRepository_SaveResponse_Call struct {
	*mock.Call
}

// SaveResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - idemKey string
//   - statusCode int
//   - res *dto.OrderResponse
//   - resultTTL time.Duration
func (_e *MockIdempotencyRepository_Expecter) SaveResponse(ctx any, idemKey any, statusCode any, res any, resultTTL any) *MockIdempotencyRepository_SaveResponse_Call {
	return &MockIdempotencyRepository_SaveResponse_Call{Call: _e.mock.On("SaveResponse", ctx, idemKey, statusCode, res, resultTTL)}
}

func (_c *MockIdempotencyRepository_SaveResponse_Call) Run(run func(ctx context.Context, idemKey string, statusCode int, res *dto.OrderResponse, resultTTL time.Duration)) *MockIdempotencyRepository_SaveResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *dto.OrderResponse
		if args[3] != nil {
			arg3 = args[3].(*dto.OrderResponse)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIdempotencyRepository_SaveResponse_Call) Return(err error) *MockIdempotencyRepository_SaveResponse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdempotencyRepository_SaveResponse_Call) RunAndReturn(run func(ctx context.Context, idemKey string, statusCode int, res *dto.OrderResponse, resultTTL time.Duration) error) *MockIdempotencyRepository_SaveResponse_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function for the type MockIdempotencyRepository
func (_mock *MockIdempotencyRepository) Unlock(ctx context.Context, idemKey string) error {
	ret := _mock.Called(ctx, idemKey)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, idemKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdempotencyRepository_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type MockIdempotencyRepository_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - ctx context.Context
//   - idemKey string
func (_e *MockIdempotencyRepository_Expecter) Unlock(ctx any, idemKey any) *MockIdempotencyRepository_Unlock_Call {
	return &MockIdempotencyRepository_Unlock_Call{Call: _e.mock.On("Unlock", ctx, idemKey)}
}

func (_c *MockIdempotencyRepository_Unlock_Call) Run(run func(ctx context.Context, idemKey string)) *MockIdempotencyRepository_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdempotencyRepository_Unlock_Call) Return(err error) *MockIdempotencyRepository_Unlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdempotencyRepository_Unlock_Call) RunAndReturn(run func(ctx context.Context, idemKey string) error) *MockIdempotencyRepository_Unlock_Call {
	_c.Call.Return(run)
	return _c
}
