// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCartService creates a new instance of MockCartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartService {
	mock := &MockCartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCartService is an autogenerated mock type for the CartService type
type MockCartService struct {
	mock.Mock
}

type MockCartService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartService) EXPECT() *MockCartService_Expecter {
	return &MockCartService_Expecter{mock: &_m.Mock}
}

// ClearCart provides a mock function for the type MockCartService
func (_mock *MockCartService) ClearCart(ctx context.Context, userID uint) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearCart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartService_ClearCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCart'
type MockCartService_ClearCart_Call struct {
	*mock.Call
}

// ClearCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockCartService_Expecter) ClearCart(ctx any, userID any) *MockCartService_ClearCart_Call {
	return &MockCartService_ClearCart_Call{Call: _e.mock.On("ClearCart", ctx, userID)}
}

func (_c *MockCartService_ClearCart_Call) Run(run func(ctx context.Context, userID uint)) *MockCartService_ClearCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartService_ClearCart_Call) Return(err error) *MockCartService_ClearCart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartService_ClearCart_Call) RunAndReturn(run func(ctx context.Context, userID uint) error) *MockCartService_ClearCart_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawCart provides a mock function for the type MockCartService
func (_mock *MockCartService) GetRawCart(ctx context.Context, userID uint) (map[uint]int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRawCart")
	}

	var r0 map[uint]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (map[uint]int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) map[uint]int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCartService_GetRawCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawCart'
type MockCartService_GetRawCart_Call struct {
	*mock.Call
}

// GetRawCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockCartService_Expecter) GetRawCart(ctx any, userID any) *MockCartService_GetRawCart_Call {
	return &MockCartService_GetRawCart_Call{Call: _e.mock.On("GetRawCart", ctx, userID)}
}

func (_c *MockCartService_GetRawCart_Call) Run(run func(ctx context.Context, userID uint)) *MockCartService_GetRawCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartService_GetRawCart_Call) Return(uintToInt map[uint]int, err error) *MockCartService_GetRawCart_Call {
	_c.Call.Return(uintToInt, err)
	return _c
}

func (_c *MockCartService_GetRawCart_Call) RunAndReturn(run func(ctx context.Context, userID uint) (map[uint]int, error)) *MockCartService_GetRawCart_Call {
	_c.Call.Return(run)
	return _c
}
