// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/e-commerce/internal/order/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// CreateOrderWithItems provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) CreateOrderWithItems(ctx context.Context, order *entity.Order, items []entity.OrderItem) error {
	ret := _mock.Called(ctx, order, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrderWithItems")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Order, []entity.OrderItem) error); ok {
		r0 = returnFunc(ctx, order, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_CreateOrderWithItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrderWithItems'
type MockOrderRepository_CreateOrderWithItems_Call struct {
	*mock.Call
}

// CreateOrderWithItems is a helper method to define mock.On call
//   - ctx context.Context
//   - order *entity.Order
//   - items []entity.OrderItem
func (_e *MockOrderRepository_Expecter) CreateOrderWithItems(ctx any, order any, items any) *MockOrderRepository_CreateOrderWithItems_Call {
	return &MockOrderRepository_CreateOrderWithItems_Call{Call: _e.mock.On("CreateOrderWithItems", ctx, order, items)}
}

func (_c *MockOrderRepository_CreateOrderWithItems_Call) Run(run func(ctx context.Context, order *entity.Order, items []entity.OrderItem)) *MockOrderRepository_CreateOrderWithItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Order
		if args[1] != nil {
			arg1 = args[1].(*entity.Order)
		}
		var arg2 []entity.OrderItem
		if args[2] != nil {
			arg2 = args[2].([]entity.OrderItem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepository_CreateOrderWithItems_Call) Return(err error) *MockOrderRepository_CreateOrderWithItems_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_CreateOrderWithItems_Call) RunAndReturn(run func(ctx context.Context, order *entity.Order, items []entity.OrderItem) error) *MockOrderRepository_CreateOrderWithItems_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) FindByID(ctx context.Context, orderID uint) (*entity.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*entity.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *entity.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockOrderRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uint
func (_e *MockOrderRepository_Expecter) FindByID(ctx any, orderID any) *MockOrderRepository_FindByID_Call {
	return &MockOrderRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, orderID)}
}

func (_c *MockOrderRepository_FindByID_Call) Run(run func(ctx context.Context, orderID uint)) *MockOrderRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_FindByID_Call) Return(order *entity.Order, err error) *MockOrderRepository_FindByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, orderID uint) (*entity.Order, error)) *MockOrderRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) FindByUserID(ctx context.Context, userID uint) ([]entity.Order, []entity.OrderItem, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []entity.Order
	var r1 []entity.OrderItem
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]entity.Order, []entity.OrderItem, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []entity.Order); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) []entity.OrderItem); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]entity.OrderItem)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOrderRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockOrderRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockOrderRepository_Expecter) FindByUserID(ctx any, userID any) *MockOrderRepository_FindByUserID_Call {
	return &MockOrderRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockOrderRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID uint)) *MockOrderRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_FindByUserID_Call) Return(orders []entity.Order, orderItems []entity.OrderItem, err error) *MockOrderRepository_FindByUserID_Call {
	_c.Call.Return(orders, orderItems, err)
	return _c
}

func (_c *MockOrderRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]entity.Order, []entity.OrderItem, error)) *MockOrderRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindItemsByOrderID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) FindItemsByOrderID(ctx context.Context, orderID uint) ([]entity.OrderItem, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindItemsByOrderID")
	}

	var r0 []entity.OrderItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]entity.OrderItem, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []entity.OrderItem); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OrderItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_FindItemsByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindItemsByOrderID'
type MockOrderRepository_FindItemsByOrderID_Call struct {
	*mock.Call
}

// FindItemsByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uint
func (_e *MockOrderRepository_Expecter) FindItemsByOrderID(ctx any, orderID any) *MockOrderRepository_FindItemsByOrderID_Call {
	return &MockOrderRepository_FindItemsByOrderID_Call{Call: _e.mock.On("FindItemsByOrderID", ctx, orderID)}
}

func (_c *MockOrderRepository_FindItemsByOrderID_Call) Run(run func(ctx context.Context, orderID uint)) *MockOrderRepository_FindItemsByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_FindItemsByOrderID_Call) Return(orderItems []entity.OrderItem, err error) *MockOrderRepository_FindItemsByOrderID_Call {
	_c.Call.Return(orderItems, err)
	return _c
}

func (_c *MockOrderRepository_FindItemsByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uint) ([]entity.OrderItem, error)) *MockOrderRepository_FindItemsByOrderID_Call {
	_c.Call.Return(run)
	return _c
}
