// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/e-commerce/internal/product/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// AdjustStock provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) AdjustStock(ctx context.Context, productID uint, quantity int) error {
	ret := _mock.Called(ctx, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AdjustStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, int) error); ok {
		r0 = returnFunc(ctx, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_AdjustStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustStock'
type MockProductRepository_AdjustStock_Call struct {
	*mock.Call
}

// AdjustStock is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uint
//   - quantity int
func (_e *MockProductRepository_Expecter) AdjustStock(ctx any, productID any, quantity any) *MockProductRepository_AdjustStock_Call {
	return &MockProductRepository_AdjustStock_Call{Call: _e.mock.On("AdjustStock", ctx, productID, quantity)}
}

func (_c *MockProductRepository_AdjustStock_Call) Run(run func(ctx context.Context, productID uint, quantity int)) *MockProductRepository_AdjustStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProductRepository_AdjustStock_Call) Return(err error) *MockProductRepository_AdjustStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_AdjustStock_Call) RunAndReturn(run func(ctx context.Context, productID uint, quantity int) error) *MockProductRepository_AdjustStock_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Create(ctx context.Context, product *entity.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product *entity.Product
func (_e *MockProductRepository_Expecter) Create(ctx any, product any) *MockProductRepository_Create_Call {
	return &MockProductRepository_Create_Call{Call: _e.mock.On("Create", ctx, product)}
}

func (_c *MockProductRepository_Create_Call) Run(run func(ctx context.Context, product *entity.Product)) *MockProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Product
		if args[1] != nil {
			arg1 = args[1].(*entity.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_Create_Call) Return(err error) *MockProductRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_Create_Call) RunAndReturn(run func(ctx context.Context, product *entity.Product) error) *MockProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DecreaseStock provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) DecreaseStock(ctx context.Context, productID uint, quantity int) error {
	ret := _mock.Called(ctx, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, int) error); ok {
		r0 = returnFunc(ctx, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_DecreaseStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecreaseStock'
type MockProductRepository_DecreaseStock_Call struct {
	*mock.Call
}

// DecreaseStock is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uint
//   - quantity int
func (_e *MockProductRepository_Expecter) DecreaseStock(ctx any, productID any, quantity any) *MockProductRepository_DecreaseStock_Call {
	return &MockProductRepository_DecreaseStock_Call{Call: _e.mock.On("DecreaseStock", ctx, productID, quantity)}
}

func (_c *MockProductRepository_DecreaseStock_Call) Run(run func(ctx context.Context, productID uint, quantity int)) *MockProductRepository_DecreaseStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProductRepository_DecreaseStock_Call) Return(err error) *MockProductRepository_DecreaseStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_DecreaseStock_Call) RunAndReturn(run func(ctx context.Context, productID uint, quantity int) error) *MockProductRepository_DecreaseStock_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Delete(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockProductRepository_Expecter) Delete(ctx any, id any) *MockProductRepository_Delete_Call {
	return &MockProductRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProductRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_Delete_Call) Return(err error) *MockProductRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) FindAll(ctx context.Context, filter *entity.ProductFilter) ([]entity.Product, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Product
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.ProductFilter) ([]entity.Product, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.ProductFilter) []entity.Product); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.ProductFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *entity.ProductFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProductRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockProductRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *entity.ProductFilter
func (_e *MockProductRepository_Expecter) FindAll(ctx any, filter any) *MockProductRepository_FindAll_Call {
	return &MockProductRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filter)}
}

func (_c *MockProductRepository_FindAll_Call) Run(run func(ctx context.Context, filter *entity.ProductFilter)) *MockProductRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.ProductFilter
		if args[1] != nil {
			arg1 = args[1].(*entity.ProductFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_FindAll_Call) Return(products []entity.Product, n int64, err error) *MockProductRepository_FindAll_Call {
	_c.Call.Return(products, n, err)
	return _c
}

func (_c *MockProductRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, filter *entity.ProductFilter) ([]entity.Product, int64, error)) *MockProductRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) FindByID(ctx context.Context, id uint) (*entity.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*entity.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *entity.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockProductRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockProductRepository_Expecter) FindByID(ctx any, id any) *MockProductRepository_FindByID_Call {
	return &MockProductRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockProductRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockProductRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_FindByID_Call) Return(product *entity.Product, err error) *MockProductRepository_FindByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (*entity.Product, error)) *MockProductRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) FindByIDs(ctx context.Context, ids []uint) ([]entity.Product, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []entity.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint) ([]entity.Product, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint) []entity.Product); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockProductRepository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockProductRepository_Expecter) FindByIDs(ctx any, ids any) *MockProductRepository_FindByIDs_Call {
	return &MockProductRepository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockProductRepository_FindByIDs_Call) Run(run func(ctx context.Context, ids []uint)) *MockProductRepository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint
		if args[1] != nil {
			arg1 = args[1].([]uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_FindByIDs_Call) Return(products []entity.Product, err error) *MockProductRepository_FindByIDs_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockProductRepository_FindByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []uint) ([]entity.Product, error)) *MockProductRepository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Update(ctx context.Context, product *entity.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - product *entity.Product
func (_e *MockProductRepository_Expecter) Update(ctx any, product any) *MockProductRepository_Update_Call {
	return &MockProductRepository_Update_Call{Call: _e.mock.On("Update", ctx, product)}
}

func (_c *MockProductRepository_Update_Call) Run(run func(ctx context.Context, product *entity.Product)) *MockProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Product
		if args[1] != nil {
			arg1 = args[1].(*entity.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_Update_Call) Return(err error) *MockProductRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_Update_Call) RunAndReturn(run func(ctx context.Context, product *entity.Product) error) *MockProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
