// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/e-commerce/internal/product/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryUsecase creates a new instance of MockCategoryUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryUsecase {
	mock := &MockCategoryUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryUsecase is an autogenerated mock type for the CategoryUsecase type
type MockCategoryUsecase struct {
	mock.Mock
}

type MockCategoryUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryUsecase) EXPECT() *MockCategoryUsecase_Expecter {
	return &MockCategoryUsecase_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function for the type MockCategoryUsecase
func (_mock *MockCategoryUsecase) CreateCategory(ctx context.Context, request *dto.CategoryRequest) (*dto.CategoryResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *dto.CategoryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CategoryRequest) (*dto.CategoryResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CategoryRequest) *dto.CategoryResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CategoryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.CategoryRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryUsecase_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type MockCategoryUsecase_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dto.CategoryRequest
func (_e *MockCategoryUsecase_Expecter) CreateCategory(ctx any, request any) *MockCategoryUsecase_CreateCategory_Call {
	return &MockCategoryUsecase_CreateCategory_Call{Call: _e.mock.On("CreateCategory", ctx, request)}
}

func (_c *MockCategoryUsecase_CreateCategory_Call) Run(run func(ctx context.Context, request *dto.CategoryRequest)) *MockCategoryUsecase_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.CategoryRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.CategoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryUsecase_CreateCategory_Call) Return(categoryResponse *dto.CategoryResponse, err error) *MockCategoryUsecase_CreateCategory_Call {
	_c.Call.Return(categoryResponse, err)
	return _c
}

func (_c *MockCategoryUsecase_CreateCategory_Call) RunAndReturn(run func(ctx context.Context, request *dto.CategoryRequest) (*dto.CategoryResponse, error)) *MockCategoryUsecase_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCategories provides a mock function for the type MockCategoryUsecase
func (_mock *MockCategoryUsecase) GetAllCategories(ctx context.Context) ([]dto.CategoryResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategories")
	}

	var r0 []dto.CategoryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dto.CategoryResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dto.CategoryResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CategoryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryUsecase_GetAllCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCategories'
type MockCategoryUsecase_GetAllCategories_Call struct {
	*mock.Call
}

// GetAllCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCategoryUsecase_Expecter) GetAllCategories(ctx any) *MockCategoryUsecase_GetAllCategories_Call {
	return &MockCategoryUsecase_GetAllCategories_Call{Call: _e.mock.On("GetAllCategories", ctx)}
}

func (_c *MockCategoryUsecase_GetAllCategories_Call) Run(run func(ctx context.Context)) *MockCategoryUsecase_GetAllCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryUsecase_GetAllCategories_Call) Return(categoryResponses []dto.CategoryResponse, err error) *MockCategoryUsecase_GetAllCategories_Call {
	_c.Call.Return(categoryResponses, err)
	return _c
}

func (_c *MockCategoryUsecase_GetAllCategories_Call) RunAndReturn(run func(ctx context.Context) ([]dto.CategoryResponse, error)) *MockCategoryUsecase_GetAllCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCategoryExists provides a mock function for the type MockCategoryUsecase
func (_mock *MockCategoryUsecase) ValidateCategoryExists(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCategoryExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryUsecase_ValidateCategoryExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCategoryExists'
type MockCategoryUsecase_ValidateCategoryExists_Call struct {
	*mock.Call
}

// ValidateCategoryExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockCategoryUsecase_Expecter) ValidateCategoryExists(ctx any, id any) *MockCategoryUsecase_ValidateCategoryExists_Call {
	return &MockCategoryUsecase_ValidateCategoryExists_Call{Call: _e.mock.On("ValidateCategoryExists", ctx, id)}
}

func (_c *MockCategoryUsecase_ValidateCategoryExists_Call) Run(run func(ctx context.Context, id uint)) *MockCategoryUsecase_ValidateCategoryExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryUsecase_ValidateCategoryExists_Call) Return(err error) *MockCategoryUsecase_ValidateCategoryExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryUsecase_ValidateCategoryExists_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockCategoryUsecase_ValidateCategoryExists_Call {
	_c.Call.Return(run)
	return _c
}
